### PR TITLE
Fingerprint atime

### PR DESCRIPTION
**Pull request by Eh2406**
This builds on and includes #14. As discussed in https://github.com/holmgr/cargo-sweep/issues/6#issuecomment-447918349, Cargo always reads the hash file in the fingerprint folder for the full transitive set of depended artifacts for every build. Thus the max atime in the fingerprint folder is the most reliable measure of witch artifacts are stale. And it is reliable enough to use with the `-s` argument.

### CODE REVIEW

**Comment by Eh2406** [comment]
I know that it is hard to keep up with OSS with the holidays. Nonetheless, I would appreciate some response to my PRs. If my experiments for how a GC can work as a cargo subcommand are out of scope for this project I understand and will reach out to other projects. If I do not hear from you in the next week I will assume this is out of scope.

**Comment by holmgr** [comment]
Decided to stay clear of coding during the holidays to really relax for a while but have slowly started coming back to it, but I have a bit of a backlog of things to handle :P
Your PR looks very good to me.

**Comment by Eh2406** [comment]
Thanks for getting back to me. That is entirely reasonable, I hope it was relaxing!

**Comment by holmgr** [comment]
Oh, it certainly was, hopefully, you had a wonderful holiday yourself!

**Pull request merged**
