### PR TITLE
--time option requires a value

### PR DESCRIPTION
**Pull request by sourcefrog**
Remove help text incorrectly indicating that it might not

### CODE REVIEW

**Comment by Eh2406** [comment]
What does it do currently if it is missing?

**Comment by sourcefrog** [comment]
```
mbp@cheery ~/src/conserve> cargo sweep -t
error: The argument '--time <days>' requires a value but none was supplied                                                                   

USAGE:
    cargo-sweep sweep <--stamp|--file|--time <days>|--installed|--toolchains <toolchains>|--maxsize <maxsize>>                               

For more information try --help
```

**Comment by sourcefrog** [comment]
Optional option-args are kind of a bad idea, anyhow, because they make the option grammar more ambiguous.

**Comment by Eh2406** [comment]
Thanks! 

I merged without noticing the CI failure. Can you submit a follow up that gets thing to build?

**Comment by sourcefrog** [comment]
Oops, sorry. Will do.

**Comment by sourcefrog** [comment]
#39

**Pull request merged**
