### PR TITLE
Fix when the `native` directory isn't present

### LINKED ISSUE #27: File not found error if used on newer target directories without native folder
Cargo no longer creates the `native` directory, which breaks cargo-sweep. The change happened in this commit https://github.com/rust-lang/cargo/pull/7227

### PR DESCRIPTION
**Pull request by coolreader18**
Resolves #27

### CODE REVIEW

**Comment by holmgr** [comment]
Hi, this looks really good :) Thanks for the PR

**Comment by coolreader18** [comment]
Thanks for merging! Would you be able to release a new version onto crates.io?

**Comment by holmgr** [comment]
Yes, I will do that as soon as I have time. Hopefully this evening :)

**Comment by holmgr** [comment]
New version (0.5.0) published @coolreader18 :)

**Pull request merged**
