### PR TITLE
Use error from stderr if stdout is empty

### LINKED ISSUE #24: Improve error handling
Right now errors seem not to be printed correctly, and cargo-sweep exits with code 0 even on error.

```text
$ cargo sweep --toolchains nightly-2019-13-13 # toolchain that does not exist
[INFO] Using specified installed toolchains: ["nightly-2019-13-13"]
[ERROR] Failed to clean "/project/target":
```

### PR DESCRIPTION
**Pull request by adumbidiot**
I believe this fixes #24.

### CODE REVIEW

**Comment by fenhl** [comment]
Indeed it does.

**Review by jyn514 — APPROVED** [review]
Thanks for the PR! It would be really nice to have tests for this behavior, but this change is obviously correct so I'll go ahead and merge for now :) let me know if you're interested in following up.

**Comment by adumbidiot** [comment]
Honestly, I wasn't sure why stdout is involved at all when it seems the stderr always has the error (from my testing). However, I assumed that this isn't always the case, as the person who wrote this block probably got an error from the stdout since thats the way they wrote that. Also, I am not sure how I would write a test for this. Would we somehow create a project with an error for sweep to find?

**Comment by jyn514** [comment]
> Would we somehow create a project with an error for sweep to find?

That was my idea, yeah :) You should be able to reproduce it consistently by adding a custom `rustc` shell script in PATH that always gives an error.

It looks like cargo-sweep only has unit tests currently, not integration tests, so we'd need to set those up - in deadlinks I use `assert_cmd` which works pretty well without much boilerplate: https://github.com/deadlinks/cargo-deadlinks/blob/73de1dfcc24c6dcb2743505c176ff96aff9ca28d/tests/broken_links.rs#L8-L28
Let me know if that sounds like a hassle and I can add this first test, and hopefully it will be easier to add more in the future :)

**Comment by adumbidiot** [comment]
Sorry, not sure if I have the time for that in the next few weeks. I'll try to implement that though if this test is still missing when I get some free time.

**Comment by fenhl** [comment]
Could we get a crates.io release with this fix please?

**Pull request merged**
