### PR TITLE
use --debug for the current verbose files output

### PR DESCRIPTION
**Pull request by juhp**
I find the default output listing every file to delete, too noisy.
So I wonder if it would be acceptable to make the default output quieter?
If not I can flip this PR to make it an opt-in `--quiet` option instead...

With this PR the default output 
- by default no longer lists each file being deleted for toolchain
  but just list the project path instead and the total size removed.
- also doesn't warn about unidentified installed toolchain (I don't use rustup but just the rustc from my distro).

'--verbose' might be a better name though it is already taken by cargo

### CODE REVIEW

**Comment by juhp** [comment]
I am afraid I pushed a couple more improvements here:
I think they are good too though somewhat separate enhancements.

**Comment by jyn514** [comment]
@juhp I see quite a lot of unrelated changes in this PR. Could you please split into each of them into a separate PR so I can review / merge them individually? It looks like this PR also contains several breaking changes which I'm not inclined to merge without a strong reason.

**Comment by juhp** [comment]
Sure, I should have a used branch, before pushing more of my changes...

**Comment by jyn514** [comment]
I'm going to close this until you get a chance to update it with only the `--debug` change (which I do think is good and useful). Feel free to reopen once you have time.

**Pull request closed without merging**
